version: '3.9'

services:
  wordpress:
    image: wordpress:6.4.3
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      VIRTUAL_HOST: cantina.local  # Dominio local personalizado
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"  # Puerto para conexión externa
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

volumes:
  db_data:
